project:
  type: website

website:
  title: "nebu"
  site-url: http://nebnebu.xyz
  description: "nebu's blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    theme:
      dark: rose-pine.scss
      light: rose-pine-dawn.scss
    css: styles.css
