name: Deploy Quarto Site to S3

on:
  push:
    branches: [ "main" ]  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Render Quarto Project
      run: |
        cd blog
        quarto render

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # replace with your AWS region

    - name: Sync to S3
      run: |
        cd blog
        aws s3 sync _site s3://nebunebu.xyz --delete
